// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package recipe

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, creatorID uuid.UUID, recipe Recipe) (*Recipe, error) {
	ret := _mock.Called(ctx, creatorID, recipe)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *Recipe
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, Recipe) (*Recipe, error)); ok {
		return returnFunc(ctx, creatorID, recipe)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, Recipe) *Recipe); ok {
		r0 = returnFunc(ctx, creatorID, recipe)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Recipe)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, Recipe) error); ok {
		r1 = returnFunc(ctx, creatorID, recipe)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - creatorID uuid.UUID
//   - recipe Recipe
func (_e *MockService_Expecter) Create(ctx any, creatorID any, recipe any) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, creatorID, recipe)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, creatorID uuid.UUID, recipe Recipe)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 Recipe
		if args[2] != nil {
			arg2 = args[2].(Recipe)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(recipe1 *Recipe, err error) *MockService_Create_Call {
	_c.Call.Return(recipe1, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, creatorID uuid.UUID, recipe Recipe) (*Recipe, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockService
func (_mock *MockService) Delete(ctx context.Context, id int, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - userID uuid.UUID
func (_e *MockService_Expecter) Delete(ctx any, id any, userID any) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", ctx, id, userID)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, id int, userID uuid.UUID)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(err error) *MockService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(ctx context.Context, id int, userID uuid.UUID) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Favorite provides a mock function for the type MockService
func (_mock *MockService) Favorite(ctx context.Context, id int, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Favorite")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Favorite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Favorite'
type MockService_Favorite_Call struct {
	*mock.Call
}

// Favorite is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - userID uuid.UUID
func (_e *MockService_Expecter) Favorite(ctx any, id any, userID any) *MockService_Favorite_Call {
	return &MockService_Favorite_Call{Call: _e.mock.On("Favorite", ctx, id, userID)}
}

func (_c *MockService_Favorite_Call) Run(run func(ctx context.Context, id int, userID uuid.UUID)) *MockService_Favorite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Favorite_Call) Return(err error) *MockService_Favorite_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Favorite_Call) RunAndReturn(run func(ctx context.Context, id int, userID uuid.UUID) error) *MockService_Favorite_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockService
func (_mock *MockService) Get(ctx context.Context, id int) (*Recipe, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *Recipe
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*Recipe, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *Recipe); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Recipe)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockService_Expecter) Get(ctx any, id any) *MockService_Get_Call {
	return &MockService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockService_Get_Call) Run(run func(ctx context.Context, id int)) *MockService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Get_Call) Return(recipe *Recipe, err error) *MockService_Get_Call {
	_c.Call.Return(recipe, err)
	return _c
}

func (_c *MockService_Get_Call) RunAndReturn(run func(ctx context.Context, id int) (*Recipe, error)) *MockService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockService
func (_mock *MockService) List(ctx context.Context, query GetRecipesQuery) ([]Recipe, int64, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []Recipe
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, GetRecipesQuery) ([]Recipe, int64, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, GetRecipesQuery) []Recipe); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Recipe)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, GetRecipesQuery) int64); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, GetRecipesQuery) error); ok {
		r2 = returnFunc(ctx, query)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - query GetRecipesQuery
func (_e *MockService_Expecter) List(ctx any, query any) *MockService_List_Call {
	return &MockService_List_Call{Call: _e.mock.On("List", ctx, query)}
}

func (_c *MockService_List_Call) Run(run func(ctx context.Context, query GetRecipesQuery)) *MockService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 GetRecipesQuery
		if args[1] != nil {
			arg1 = args[1].(GetRecipesQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_List_Call) Return(recipes []Recipe, n int64, err error) *MockService_List_Call {
	_c.Call.Return(recipes, n, err)
	return _c
}

func (_c *MockService_List_Call) RunAndReturn(run func(ctx context.Context, query GetRecipesQuery) ([]Recipe, int64, error)) *MockService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Replace provides a mock function for the type MockService
func (_mock *MockService) Replace(ctx context.Context, id int, userID uuid.UUID, recipe Recipe) (*Recipe, error) {
	ret := _mock.Called(ctx, id, userID, recipe)

	if len(ret) == 0 {
		panic("no return value specified for Replace")
	}

	var r0 *Recipe
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, uuid.UUID, Recipe) (*Recipe, error)); ok {
		return returnFunc(ctx, id, userID, recipe)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, uuid.UUID, Recipe) *Recipe); ok {
		r0 = returnFunc(ctx, id, userID, recipe)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Recipe)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, uuid.UUID, Recipe) error); ok {
		r1 = returnFunc(ctx, id, userID, recipe)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Replace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Replace'
type MockService_Replace_Call struct {
	*mock.Call
}

// Replace is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - userID uuid.UUID
//   - recipe Recipe
func (_e *MockService_Expecter) Replace(ctx any, id any, userID any, recipe any) *MockService_Replace_Call {
	return &MockService_Replace_Call{Call: _e.mock.On("Replace", ctx, id, userID, recipe)}
}

func (_c *MockService_Replace_Call) Run(run func(ctx context.Context, id int, userID uuid.UUID, recipe Recipe)) *MockService_Replace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 Recipe
		if args[3] != nil {
			arg3 = args[3].(Recipe)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_Replace_Call) Return(recipe1 *Recipe, err error) *MockService_Replace_Call {
	_c.Call.Return(recipe1, err)
	return _c
}

func (_c *MockService_Replace_Call) RunAndReturn(run func(ctx context.Context, id int, userID uuid.UUID, recipe Recipe) (*Recipe, error)) *MockService_Replace_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, recipe Recipe) (*Recipe, error) {
	ret := _mock.Called(ctx, recipe)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *Recipe
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Recipe) (*Recipe, error)); ok {
		return returnFunc(ctx, recipe)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Recipe) *Recipe); ok {
		r0 = returnFunc(ctx, recipe)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Recipe)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Recipe) error); ok {
		r1 = returnFunc(ctx, recipe)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - recipe Recipe
func (_e *MockRepository_Expecter) Create(ctx any, recipe any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, recipe)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, recipe Recipe)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Recipe
		if args[1] != nil {
			arg1 = args[1].(Recipe)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(recipe1 *Recipe, err error) *MockRepository_Create_Call {
	_c.Call.Return(recipe1, err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, recipe Recipe) (*Recipe, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRepository
func (_mock *MockRepository) Delete(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockRepository_Expecter) Delete(ctx any, id any) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(err error) *MockRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DifficultyExists provides a mock function for the type MockRepository
func (_mock *MockRepository) DifficultyExists(ctx context.Context, id string) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DifficultyExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_DifficultyExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DifficultyExists'
type MockRepository_DifficultyExists_Call struct {
	*mock.Call
}

// DifficultyExists is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) DifficultyExists(ctx any, id any) *MockRepository_DifficultyExists_Call {
	return &MockRepository_DifficultyExists_Call{Call: _e.mock.On("DifficultyExists", ctx, id)}
}

func (_c *MockRepository_DifficultyExists_Call) Run(run func(ctx context.Context, id string)) *MockRepository_DifficultyExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DifficultyExists_Call) Return(b bool, err error) *MockRepository_DifficultyExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_DifficultyExists_Call) RunAndReturn(run func(ctx context.Context, id string) (bool, error)) *MockRepository_DifficultyExists_Call {
	_c.Call.Return(run)
	return _c
}

// Favorite provides a mock function for the type MockRepository
func (_mock *MockRepository) Favorite(ctx context.Context, userID uuid.UUID, recipeID int) error {
	ret := _mock.Called(ctx, userID, recipeID)

	if len(ret) == 0 {
		panic("no return value specified for Favorite")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) error); ok {
		r0 = returnFunc(ctx, userID, recipeID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Favorite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Favorite'
type MockRepository_Favorite_Call struct {
	*mock.Call
}

// Favorite is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - recipeID int
func (_e *MockRepository_Expecter) Favorite(ctx any, userID any, recipeID any) *MockRepository_Favorite_Call {
	return &MockRepository_Favorite_Call{Call: _e.mock.On("Favorite", ctx, userID, recipeID)}
}

func (_c *MockRepository_Favorite_Call) Run(run func(ctx context.Context, userID uuid.UUID, recipeID int)) *MockRepository_Favorite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Favorite_Call) Return(err error) *MockRepository_Favorite_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Favorite_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, recipeID int) error) *MockRepository_Favorite_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByID(ctx context.Context, id int) (*Recipe, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *Recipe
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*Recipe, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *Recipe); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Recipe)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockRepository_Expecter) FindByID(ctx any, id any) *MockRepository_FindByID_Call {
	return &MockRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRepository_FindByID_Call) Run(run func(ctx context.Context, id int)) *MockRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByID_Call) Return(recipe *Recipe, err error) *MockRepository_FindByID_Call {
	_c.Call.Return(recipe, err)
	return _c
}

func (_c *MockRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*Recipe, error)) *MockRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// HasActiveReferences provides a mock function for the type MockRepository
func (_mock *MockRepository) HasActiveReferences(ctx context.Context, difficultyID string, durationID string) (bool, error) {
	ret := _mock.Called(ctx, difficultyID, durationID)

	if len(ret) == 0 {
		panic("no return value specified for HasActiveReferences")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, difficultyID, durationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, difficultyID, durationID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, difficultyID, durationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_HasActiveReferences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasActiveReferences'
type MockRepository_HasActiveReferences_Call struct {
	*mock.Call
}

// HasActiveReferences is a helper method to define mock.On call
//   - ctx context.Context
//   - difficultyID string
//   - durationID string
func (_e *MockRepository_Expecter) HasActiveReferences(ctx any, difficultyID any, durationID any) *MockRepository_HasActiveReferences_Call {
	return &MockRepository_HasActiveReferences_Call{Call: _e.mock.On("HasActiveReferences", ctx, difficultyID, durationID)}
}

func (_c *MockRepository_HasActiveReferences_Call) Run(run func(ctx context.Context, difficultyID string, durationID string)) *MockRepository_HasActiveReferences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_HasActiveReferences_Call) Return(b bool, err error) *MockRepository_HasActiveReferences_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_HasActiveReferences_Call) RunAndReturn(run func(ctx context.Context, difficultyID string, durationID string) (bool, error)) *MockRepository_HasActiveReferences_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRepository
func (_mock *MockRepository) List(ctx context.Context, query GetRecipesQuery) ([]Recipe, int64, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []Recipe
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, GetRecipesQuery) ([]Recipe, int64, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, GetRecipesQuery) []Recipe); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Recipe)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, GetRecipesQuery) int64); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, GetRecipesQuery) error); ok {
		r2 = returnFunc(ctx, query)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - query GetRecipesQuery
func (_e *MockRepository_Expecter) List(ctx any, query any) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx, query)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context, query GetRecipesQuery)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 GetRecipesQuery
		if args[1] != nil {
			arg1 = args[1].(GetRecipesQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(recipes []Recipe, n int64, err error) *MockRepository_List_Call {
	_c.Call.Return(recipes, n, err)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(ctx context.Context, query GetRecipesQuery) ([]Recipe, int64, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Replace provides a mock function for the type MockRepository
func (_mock *MockRepository) Replace(ctx context.Context, recipe Recipe) (*Recipe, error) {
	ret := _mock.Called(ctx, recipe)

	if len(ret) == 0 {
		panic("no return value specified for Replace")
	}

	var r0 *Recipe
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Recipe) (*Recipe, error)); ok {
		return returnFunc(ctx, recipe)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Recipe) *Recipe); ok {
		r0 = returnFunc(ctx, recipe)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Recipe)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Recipe) error); ok {
		r1 = returnFunc(ctx, recipe)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Replace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Replace'
type MockRepository_Replace_Call struct {
	*mock.Call
}

// Replace is a helper method to define mock.On call
//   - ctx context.Context
//   - recipe Recipe
func (_e *MockRepository_Expecter) Replace(ctx any, recipe any) *MockRepository_Replace_Call {
	return &MockRepository_Replace_Call{Call: _e.mock.On("Replace", ctx, recipe)}
}

func (_c *MockRepository_Replace_Call) Run(run func(ctx context.Context, recipe Recipe)) *MockRepository_Replace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Recipe
		if args[1] != nil {
			arg1 = args[1].(Recipe)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Replace_Call) Return(recipe1 *Recipe, err error) *MockRepository_Replace_Call {
	_c.Call.Return(recipe1, err)
	return _c
}

func (_c *MockRepository_Replace_Call) RunAndReturn(run func(ctx context.Context, recipe Recipe) (*Recipe, error)) *MockRepository_Replace_Call {
	_c.Call.Return(run)
	return _c
}
