// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package recipe

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, creatorID uuid.UUID, recipe Recipe) (*Recipe, error) {
	ret := _mock.Called(ctx, creatorID, recipe)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *Recipe
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, Recipe) (*Recipe, error)); ok {
		return returnFunc(ctx, creatorID, recipe)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, Recipe) *Recipe); ok {
		r0 = returnFunc(ctx, creatorID, recipe)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Recipe)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, Recipe) error); ok {
		r1 = returnFunc(ctx, creatorID, recipe)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - creatorID uuid.UUID
//   - recipe Recipe
func (_e *MockService_Expecter) Create(ctx any, creatorID any, recipe any) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, creatorID, recipe)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, creatorID uuid.UUID, recipe Recipe)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 Recipe
		if args[2] != nil {
			arg2 = args[2].(Recipe)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(recipe1 *Recipe, err error) *MockService_Create_Call {
	_c.Call.Return(recipe1, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, creatorID uuid.UUID, recipe Recipe) (*Recipe, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, recipe Recipe) (*Recipe, error) {
	ret := _mock.Called(ctx, recipe)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *Recipe
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Recipe) (*Recipe, error)); ok {
		return returnFunc(ctx, recipe)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Recipe) *Recipe); ok {
		r0 = returnFunc(ctx, recipe)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Recipe)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Recipe) error); ok {
		r1 = returnFunc(ctx, recipe)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - recipe Recipe
func (_e *MockRepository_Expecter) Create(ctx any, recipe any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, recipe)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, recipe Recipe)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Recipe
		if args[1] != nil {
			arg1 = args[1].(Recipe)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(recipe1 *Recipe, err error) *MockRepository_Create_Call {
	_c.Call.Return(recipe1, err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, recipe Recipe) (*Recipe, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// HasActiveReferences provides a mock function for the type MockRepository
func (_mock *MockRepository) HasActiveReferences(ctx context.Context, difficultyID string, durationID string) (bool, error) {
	ret := _mock.Called(ctx, difficultyID, durationID)

	if len(ret) == 0 {
		panic("no return value specified for HasActiveReferences")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, difficultyID, durationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, difficultyID, durationID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, difficultyID, durationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_HasActiveReferences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasActiveReferences'
type MockRepository_HasActiveReferences_Call struct {
	*mock.Call
}

// HasActiveReferences is a helper method to define mock.On call
//   - ctx context.Context
//   - difficultyID string
//   - durationID string
func (_e *MockRepository_Expecter) HasActiveReferences(ctx any, difficultyID any, durationID any) *MockRepository_HasActiveReferences_Call {
	return &MockRepository_HasActiveReferences_Call{Call: _e.mock.On("HasActiveReferences", ctx, difficultyID, durationID)}
}

func (_c *MockRepository_HasActiveReferences_Call) Run(run func(ctx context.Context, difficultyID string, durationID string)) *MockRepository_HasActiveReferences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_HasActiveReferences_Call) Return(b bool, err error) *MockRepository_HasActiveReferences_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_HasActiveReferences_Call) RunAndReturn(run func(ctx context.Context, difficultyID string, durationID string) (bool, error)) *MockRepository_HasActiveReferences_Call {
	_c.Call.Return(run)
	return _c
}
