// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package middleware

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserResolver creates a new instance of MockUserResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserResolver {
	mock := &MockUserResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserResolver is an autogenerated mock type for the UserResolver type
type MockUserResolver struct {
	mock.Mock
}

type MockUserResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserResolver) EXPECT() *MockUserResolver_Expecter {
	return &MockUserResolver_Expecter{mock: &_m.Mock}
}

// ResolveID provides a mock function for the type MockUserResolver
func (_mock *MockUserResolver) ResolveID(ctx context.Context, uid string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for ResolveID")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserResolver_ResolveID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveID'
type MockUserResolver_ResolveID_Call struct {
	*mock.Call
}

// ResolveID is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockUserResolver_Expecter) ResolveID(ctx any, uid any) *MockUserResolver_ResolveID_Call {
	return &MockUserResolver_ResolveID_Call{Call: _e.mock.On("ResolveID", ctx, uid)}
}

func (_c *MockUserResolver_ResolveID_Call) Run(run func(ctx context.Context, uid string)) *MockUserResolver_ResolveID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserResolver_ResolveID_Call) Return(uUID uuid.UUID, err error) *MockUserResolver_ResolveID_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockUserResolver_ResolveID_Call) RunAndReturn(run func(ctx context.Context, uid string) (uuid.UUID, error)) *MockUserResolver_ResolveID_Call {
	_c.Call.Return(run)
	return _c
}
