// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"
	"time"
	"wongnok/internal/user"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// BuildLoginURL provides a mock function for the type MockService
func (_mock *MockService) BuildLoginURL(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BuildLoginURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_BuildLoginURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildLoginURL'
type MockService_BuildLoginURL_Call struct {
	*mock.Call
}

// BuildLoginURL is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) BuildLoginURL(ctx any) *MockService_BuildLoginURL_Call {
	return &MockService_BuildLoginURL_Call{Call: _e.mock.On("BuildLoginURL", ctx)}
}

func (_c *MockService_BuildLoginURL_Call) Run(run func(ctx context.Context)) *MockService_BuildLoginURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_BuildLoginURL_Call) Return(s string, err error) *MockService_BuildLoginURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_BuildLoginURL_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockService_BuildLoginURL_Call {
	_c.Call.Return(run)
	return _c
}

// ExchangeTicket provides a mock function for the type MockService
func (_mock *MockService) ExchangeTicket(ctx context.Context, ticket string) (Credential, error) {
	ret := _mock.Called(ctx, ticket)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeTicket")
	}

	var r0 Credential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (Credential, error)); ok {
		return returnFunc(ctx, ticket)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) Credential); ok {
		r0 = returnFunc(ctx, ticket)
	} else {
		r0 = ret.Get(0).(Credential)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ticket)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ExchangeTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeTicket'
type MockService_ExchangeTicket_Call struct {
	*mock.Call
}

// ExchangeTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - ticket string
func (_e *MockService_Expecter) ExchangeTicket(ctx any, ticket any) *MockService_ExchangeTicket_Call {
	return &MockService_ExchangeTicket_Call{Call: _e.mock.On("ExchangeTicket", ctx, ticket)}
}

func (_c *MockService_ExchangeTicket_Call) Run(run func(ctx context.Context, ticket string)) *MockService_ExchangeTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ExchangeTicket_Call) Return(credential Credential, err error) *MockService_ExchangeTicket_Call {
	_c.Call.Return(credential, err)
	return _c
}

func (_c *MockService_ExchangeTicket_Call) RunAndReturn(run func(ctx context.Context, ticket string) (Credential, error)) *MockService_ExchangeTicket_Call {
	_c.Call.Return(run)
	return _c
}

// HandleCallback provides a mock function for the type MockService
func (_mock *MockService) HandleCallback(ctx context.Context, code string, state string) (string, error) {
	ret := _mock.Called(ctx, code, state)

	if len(ret) == 0 {
		panic("no return value specified for HandleCallback")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, code, state)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, code, state)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, code, state)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_HandleCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleCallback'
type MockService_HandleCallback_Call struct {
	*mock.Call
}

// HandleCallback is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - state string
func (_e *MockService_Expecter) HandleCallback(ctx any, code any, state any) *MockService_HandleCallback_Call {
	return &MockService_HandleCallback_Call{Call: _e.mock.On("HandleCallback", ctx, code, state)}
}

func (_c *MockService_HandleCallback_Call) Run(run func(ctx context.Context, code string, state string)) *MockService_HandleCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_HandleCallback_Call) Return(s string, err error) *MockService_HandleCallback_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_HandleCallback_Call) RunAndReturn(run func(ctx context.Context, code string, state string) (string, error)) *MockService_HandleCallback_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockService
func (_mock *MockService) Logout(ctx context.Context, refreshToken string) error {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockService_Expecter) Logout(ctx any, refreshToken any) *MockService_Logout_Call {
	return &MockService_Logout_Call{Call: _e.mock.On("Logout", ctx, refreshToken)}
}

func (_c *MockService_Logout_Call) Run(run func(ctx context.Context, refreshToken string)) *MockService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Logout_Call) Return(err error) *MockService_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Logout_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) error) *MockService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ConsumeState provides a mock function for the type MockRepository
func (_mock *MockRepository) ConsumeState(ctx context.Context, state string) error {
	ret := _mock.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_ConsumeState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeState'
type MockRepository_ConsumeState_Call struct {
	*mock.Call
}

// ConsumeState is a helper method to define mock.On call
//   - ctx context.Context
//   - state string
func (_e *MockRepository_Expecter) ConsumeState(ctx any, state any) *MockRepository_ConsumeState_Call {
	return &MockRepository_ConsumeState_Call{Call: _e.mock.On("ConsumeState", ctx, state)}
}

func (_c *MockRepository_ConsumeState_Call) Run(run func(ctx context.Context, state string)) *MockRepository_ConsumeState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ConsumeState_Call) Return(err error) *MockRepository_ConsumeState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_ConsumeState_Call) RunAndReturn(run func(ctx context.Context, state string) error) *MockRepository_ConsumeState_Call {
	_c.Call.Return(run)
	return _c
}

// ConsumeTicket provides a mock function for the type MockRepository
func (_mock *MockRepository) ConsumeTicket(ctx context.Context, ticket string) (Credential, error) {
	ret := _mock.Called(ctx, ticket)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeTicket")
	}

	var r0 Credential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (Credential, error)); ok {
		return returnFunc(ctx, ticket)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) Credential); ok {
		r0 = returnFunc(ctx, ticket)
	} else {
		r0 = ret.Get(0).(Credential)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ticket)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ConsumeTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeTicket'
type MockRepository_ConsumeTicket_Call struct {
	*mock.Call
}

// ConsumeTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - ticket string
func (_e *MockRepository_Expecter) ConsumeTicket(ctx any, ticket any) *MockRepository_ConsumeTicket_Call {
	return &MockRepository_ConsumeTicket_Call{Call: _e.mock.On("ConsumeTicket", ctx, ticket)}
}

func (_c *MockRepository_ConsumeTicket_Call) Run(run func(ctx context.Context, ticket string)) *MockRepository_ConsumeTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ConsumeTicket_Call) Return(credential Credential, err error) *MockRepository_ConsumeTicket_Call {
	_c.Call.Return(credential, err)
	return _c
}

func (_c *MockRepository_ConsumeTicket_Call) RunAndReturn(run func(ctx context.Context, ticket string) (Credential, error)) *MockRepository_ConsumeTicket_Call {
	_c.Call.Return(run)
	return _c
}

// SaveState provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveState(ctx context.Context, state string, ttl time.Duration) error {
	ret := _mock.Called(ctx, state, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SaveState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, state, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SaveState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveState'
type MockRepository_SaveState_Call struct {
	*mock.Call
}

// SaveState is a helper method to define mock.On call
//   - ctx context.Context
//   - state string
//   - ttl time.Duration
func (_e *MockRepository_Expecter) SaveState(ctx any, state any, ttl any) *MockRepository_SaveState_Call {
	return &MockRepository_SaveState_Call{Call: _e.mock.On("SaveState", ctx, state, ttl)}
}

func (_c *MockRepository_SaveState_Call) Run(run func(ctx context.Context, state string, ttl time.Duration)) *MockRepository_SaveState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_SaveState_Call) Return(err error) *MockRepository_SaveState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SaveState_Call) RunAndReturn(run func(ctx context.Context, state string, ttl time.Duration) error) *MockRepository_SaveState_Call {
	_c.Call.Return(run)
	return _c
}

// SaveTicket provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveTicket(ctx context.Context, ticket string, credential Credential, ttl time.Duration) error {
	ret := _mock.Called(ctx, ticket, credential, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SaveTicket")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, Credential, time.Duration) error); ok {
		r0 = returnFunc(ctx, ticket, credential, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SaveTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveTicket'
type MockRepository_SaveTicket_Call struct {
	*mock.Call
}

// SaveTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - ticket string
//   - credential Credential
//   - ttl time.Duration
func (_e *MockRepository_Expecter) SaveTicket(ctx any, ticket any, credential any, ttl any) *MockRepository_SaveTicket_Call {
	return &MockRepository_SaveTicket_Call{Call: _e.mock.On("SaveTicket", ctx, ticket, credential, ttl)}
}

func (_c *MockRepository_SaveTicket_Call) Run(run func(ctx context.Context, ticket string, credential Credential, ttl time.Duration)) *MockRepository_SaveTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 Credential
		if args[2] != nil {
			arg2 = args[2].(Credential)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_SaveTicket_Call) Return(err error) *MockRepository_SaveTicket_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SaveTicket_Call) RunAndReturn(run func(ctx context.Context, ticket string, credential Credential, ttl time.Duration) error) *MockRepository_SaveTicket_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// UpsertFromKeycloak provides a mock function for the type MockUserService
func (_mock *MockUserService) UpsertFromKeycloak(ctx context.Context, kuser user.KeycloakUser) error {
	ret := _mock.Called(ctx, kuser)

	if len(ret) == 0 {
		panic("no return value specified for UpsertFromKeycloak")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.KeycloakUser) error); ok {
		r0 = returnFunc(ctx, kuser)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_UpsertFromKeycloak_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertFromKeycloak'
type MockUserService_UpsertFromKeycloak_Call struct {
	*mock.Call
}

// UpsertFromKeycloak is a helper method to define mock.On call
//   - ctx context.Context
//   - kuser user.KeycloakUser
func (_e *MockUserService_Expecter) UpsertFromKeycloak(ctx any, kuser any) *MockUserService_UpsertFromKeycloak_Call {
	return &MockUserService_UpsertFromKeycloak_Call{Call: _e.mock.On("UpsertFromKeycloak", ctx, kuser)}
}

func (_c *MockUserService_UpsertFromKeycloak_Call) Run(run func(ctx context.Context, kuser user.KeycloakUser)) *MockUserService_UpsertFromKeycloak_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.KeycloakUser
		if args[1] != nil {
			arg1 = args[1].(user.KeycloakUser)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_UpsertFromKeycloak_Call) Return(err error) *MockUserService_UpsertFromKeycloak_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_UpsertFromKeycloak_Call) RunAndReturn(run func(ctx context.Context, kuser user.KeycloakUser) error) *MockUserService_UpsertFromKeycloak_Call {
	_c.Call.Return(run)
	return _c
}
